# params.yaml

data:
  model_path: model/ECC2comp_configured
  vman: ACKr
  condition: anaerobic
  n_samples: 10000
  objective: EX_Biomass

training:
  hidden_dim: 4
  epochs: 501
  patience: 50
  lr: 0.001

optimize:
  t_start: 0.0
  t_end: 15.0          # <-- change to 24.0 later
  num_intervals: 3  # <-- change to 40 later
  n_eval: 1000
  objective: ethanol
  initial_state: 10.0 0.0 0.01
