# params.yaml

data:
  model_path: model/iML1515.xml
  vman: ACKr
  condition: anaerobic
  n_samples: 1000

training:
  hidden_dim: 4
  epochs: 500
  patience: 50
  lr: 0.001

optimize:
  t_start: 0.0
  t_end: 12.0          # <-- change to 24.0 later
  num_intervals: 20  # <-- change to 40 later
  n_eval: 1000
  bounds_lower: -32.0
  bounds_upper: 12.0
  initial_state: 10.0 0.0 0.01
