# params.yaml

data:
  vman: PYK
  condition: anaerobic
  n_samples: 1000

training:
  hidden_dim: 4
  epochs: 5000
  patience: 50
  lr: 0.001

optimize:
  t_start: 0.0
  t_end: 24          # <-- change to 24.0 later
  num_intervals: 40  # <-- change to 40 later
  n_eval: 200
  bounds_lower: -1.0
  bounds_upper: 1.0
  initial_state: 10.0 0.0 0.01
