#!/usr/bin/env python
"""
Stage 3b: Flux-map visualisation for the iJO1366 surrogate.

For 4 evenly-spaced LDH_D values, plots ACKr vs each output flux as 1-D slices:
  - Figure 1 (ground_truth.png): scatter from training data filtered to each LDH_D band
  - Figure 2 (surrogate.png):   dense line generated by evaluating the trained NN

Both figures are 2×2 grids, one subplot per output flux (bio, ac, co2, etoh).

Usage:
    python scripts/ijo1366_plot_flux_maps.py
    python scripts/ijo1366_plot_flux_maps.py --n-ldh-slices 4 --band-fraction 0.12
"""

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from flux_config_ijo1366 import INPUT_FLUX_IDS, OUTPUT_LABELS
from runtime_utils import PLOT_DIR, ensure_output_dirs, load_surrogate_checkpoint, surrogate_predict
from surrogateNN import SurrogateNN


# ── helpers ──────────────────────────────────────────────────────────────────

def _predict_sweep(model_nn, x_scaler, y_scaler, ackr_vals, ldh_val):
    """Surrogate sweep over ACKr at a fixed LDH_D; softplus floor applied via surrogate_predict."""
    X_sweep = np.column_stack([ackr_vals, np.full_like(ackr_vals, ldh_val)])
    return surrogate_predict(model_nn, x_scaler, y_scaler, X_sweep)


def _make_figure(title):
    fig, axes = plt.subplots(2, 2, figsize=(10, 7), constrained_layout=True)
    fig.suptitle(title, fontsize=13)
    return fig, axes.flatten()


def _label_axes(axes, output_labels, ackr_label):
    for ax, lbl in zip(axes, output_labels):
        ax.set_xlabel(ackr_label)
        ax.set_ylabel(f"flux  [{lbl}]")
        ax.set_title(lbl)
        ax.legend(fontsize=7, loc="best")


# ── main ─────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-path", type=Path,
                        default=REPO_ROOT / "data" / "ijo1366_anaerobic.npz")
    parser.add_argument("--checkpoint", type=Path,
                        default=REPO_ROOT / "trained_models" / "ijo1366_anaerobic_hidden-16.pt")
    parser.add_argument("--outdir", type=Path,
                        default=PLOT_DIR / "ijo1366_flux_maps")
    parser.add_argument("--n-ldh-slices", type=int, default=4,
                        help="Number of LDH_D values to slice at (default: 4)")
    parser.add_argument("--n-ackr-sweep", type=int, default=300,
                        help="ACKr grid points for surrogate lines (default: 300)")
    parser.add_argument("--band-fraction", type=float, default=0.12,
                        help="Half-width of LDH_D filter band as fraction of range (default: 0.12)")
    return parser.parse_args()


def main():
    args = parse_args()
    ensure_output_dirs()
    args.outdir.mkdir(parents=True, exist_ok=True)

    # ── load training data ───────────────────────────────────────────────────
    data = np.load(args.data_path)
    X = data["X"]                      # (n_feasible, 2)
    Y = data["Y"]                      # (n_feasible, 4)
    feasible_range = data["feasible_range"]   # (2, 2): [[ackr_lo, ackr_hi], [ldh_lo, ldh_hi]]

    ackr_idx = INPUT_FLUX_IDS.index("ACKr")
    ldh_idx  = INPUT_FLUX_IDS.index("LDH_D")
    ackr_lo, ackr_hi = feasible_range[ackr_idx]
    ldh_lo,  ldh_hi  = feasible_range[ldh_idx]

    ldh_values = np.linspace(ldh_lo, ldh_hi, args.n_ldh_slices)
    band_half  = args.band_fraction * (ldh_hi - ldh_lo)

    print(f"ACKr range   : [{ackr_lo:.3f}, {ackr_hi:.3f}]")
    print(f"LDH_D range  : [{ldh_lo:.3f}, {ldh_hi:.3f}]")
    print(f"LDH_D slices : {np.round(ldh_values, 3).tolist()}")
    print(f"Band half-w  : {band_half:.3f}")

    # ── load surrogate ───────────────────────────────────────────────────────
    model_nn, x_scaler, y_scaler, _ = load_surrogate_checkpoint(
        args.checkpoint, SurrogateNN
    )
    ackr_sweep = np.linspace(ackr_lo, ackr_hi, args.n_ackr_sweep)

    # ── colour cycle (one colour per LDH_D slice) ───────────────────────────
    colours = plt.cm.viridis(np.linspace(0.15, 0.85, args.n_ldh_slices))

    # ── Figure 1: ground truth (scatter from training data) ─────────────────
    fig_gt, axes_gt = _make_figure("Ground truth  (training data)")

    for colour, ldh_val in zip(colours, ldh_values):
        mask = np.abs(X[:, ldh_idx] - ldh_val) <= band_half
        n_pts = mask.sum()
        label = f"LDH_D≈{ldh_val:.2f}  (n={n_pts})"
        x_sub = X[mask, ackr_idx]
        y_sub = Y[mask]
        order = np.argsort(x_sub)
        for ax, k in zip(axes_gt, range(len(OUTPUT_LABELS))):
            ax.scatter(x_sub[order], y_sub[order, k],
                       s=8, alpha=0.55, color=colour, label=label)

    _label_axes(axes_gt, OUTPUT_LABELS, "ACKr  [mmol/gDW/h]")
    gt_path = args.outdir / "ground_truth.png"
    fig_gt.savefig(gt_path, dpi=150)
    plt.close(fig_gt)
    print(f"Saved: {gt_path}")

    # ── Figure 2: surrogate predictions (dense lines) ───────────────────────
    fig_sr, axes_sr = _make_figure("Surrogate predictions")

    for colour, ldh_val in zip(colours, ldh_values):
        label = f"LDH_D={ldh_val:.2f}"
        Y_pred = _predict_sweep(model_nn, x_scaler, y_scaler, ackr_sweep, ldh_val)
        for ax, k in zip(axes_sr, range(len(OUTPUT_LABELS))):
            ax.plot(ackr_sweep, Y_pred[:, k],
                    color=colour, linewidth=1.4, label=label)

    _label_axes(axes_sr, OUTPUT_LABELS, "ACKr  [mmol/gDW/h]")
    sr_path = args.outdir / "surrogate.png"
    fig_sr.savefig(sr_path, dpi=150)
    plt.close(fig_sr)
    print(f"Saved: {sr_path}")

    print(f"\nDone. Both plots in {args.outdir}")


if __name__ == "__main__":
    main()
